### PR TITLE
fix tests for pyls-0.33.1

### LINKED ISSUE #24: Not compatible with recent pyls versions
```
TypeError: __init__() missing 1 required positional argument: 'workspace'
```

This is the unittest log
[log.txt](https://github.com/rupert/pyls-black/files/4787421/log.txt)

I am currently testing pyls 0.33.1

### PR DESCRIPTION
**Pull request by betaboon**
fixes #24 

incompatibility got introduced by upstream https://github.com/palantir/python-language-server/commit/2fb2c8123396407147c911d0e70999008c4a9046

### CODE REVIEW

**Comment by Mic92** [comment]
I think we need a release for this.

**Comment by betaboon** [comment]
@rupert yeah we need a release for that. I've come from the nixos-community as `pyls-black` has been marked broken by us. we prefer building tagged-releases.

**Comment by rupert** [comment]
@Mic92 @betaboon hey, I've released `0.4.6` which includes these changes and some other maintenance.

* PyPI: [`0.4.6`](https://pypi.org/project/pyls-black/0.4.6/)
* GitHub Release: [`0.4.6`](https://github.com/rupert/pyls-black/releases/tag/v0.4.6) and [`0.4.5`](https://github.com/rupert/pyls-black/releases/tag/v0.4.5)

**Comment by betaboon** [comment]
@rupert thank you very much

**Pull request merged**
